priorities:
  relocation: "Relocate"
  family_ties: "Family Ties"
  individuality: "Individuality"
  romance: "Romance"
  wedding_planning: "Wedding Planning"
  domestic_chores: "Domestic Chores"
  financial_security: "Financial Security"
  career: "Career"
  in_laws: "In laws"
  kids: "Kids"
  pre_nuptial_agreement: "Pre nuptial agreement"
  further_education: "Further education"

helper:
  relocation: "Can you relocate"
  joint_family: "Joint Family or Nuclear Family"
  inlaws_interference: "In laws interfernce"
  further_education: "Spouse's further education"
  kids: "Thoughts on kids"
  opinion_on_sex: "Opinion on sex"
  gender_expectations: "Gender based expectations"
  primary_bread_winner: "Primary bread winner"
  independence: "Independence"
  career_priority: "Career's priority"
  financial_stability: "Financial stability"
  romance: "Romance in relationship"
  interests: "Personal interests"
  virginity: "Opinion on virginity"
  chivalry: "Chivalrous or not"
  decisiveness: "Ability to decide"
  family_background: "Family background"
