priorities:
  relocation: "Can you relocate"
  joint_family: "Joint or Nuclear Family"
  inlaws_interference: "In laws interference"
  further_education: "Spouse's further education"
  kids: "Thoughts on kids"
  opinion_on_sex: "Opinion on sex"
  gender_expectations: "Gender based expectations"
  primary_bread_winner: "Primary bread winner"
  independence: "Independence"
  career_priority: "Career's priority"
  financial_stability: "Financial stability"
  romance: "Romance in relationship"
  interests: "Personal interests"
  virginity: "Opinion on virginity"
  chivalry: "Chivalrous or not"
  decisiveness: "Ability to decide"
  family_background: "Family background"

helper:
  relocation: "Can you relocate"
  joint_family: "Joint Family or Nuclear Family"
  inlaws_interference: "In laws interfernce"
  further_education: "Spouse's further education"
  kids: "Thoughts on kids"
  opinion_on_sex: "Opinion on sex"
  gender_expectations: "Gender based expectations"
  primary_bread_winner: "Primary bread winner"
  independence: "Independence"
  career_priority: "Career's priority"
  financial_stability: "Financial stability"
  romance: "Romance in relationship"
  interests: "Personal interests"
  virginity: "Opinion on virginity"
  chivalry: "Chivalrous or not"
  decisiveness: "Ability to decide"
  family_background: "Family background"
