development:
  host: http://localhost
  port: 8983


production:
  host: http://localhost
  port: 8983

basic_params:
  defType: dismax
  debugQuery: on
  fl: "*,score"
  indent: on
  
keyword_search:
  fields:
    - u_dream^3.0
    - u_profession^2.5
    - u_ideal_marriage^2.75
    - u_education^2.0
    - u_location^1.0
    - u_hobbies^2.0
  defType: edismax
  rows: 20
  fl:
    - id
    - score



advanced_search:
  defType: edismax
  rows: 20
  fl:
    - id
    - score
  fields:
    - hobbies
    - profession
    - specific_interest
    - location
    - spouse_preference
    - family_preference
    - ideal_marriage
    - ideal_partner
    - education
    - further_education


recos_on_save:
  defType: edismax
  rows: 5
  fl:
    - id
    - score
  fields:
    - hobbies
    - profession
    - location
    - spouse_preference
    - ideal_marriage
    - virginity_opinion
    - sex
    - education
    - further_education
    - family_preference

