professions:
  - painter
  - artist
  - musician
  - software developer


relocate:
  1: I would like to stay in my current city
  2: I can try that
  3: "Doesn't matter"


spouse_pref:
  1: Working
  2: Home Maker
  3: "Doesn't matter"


further_education:
  1: OK


family_preference:
  1: Joint will do
  2: Prefer Nuclear
  3: Prefer spouse only
  4: "Doesn't matter"

sex:
  'ma': Male
  'fe' : Female

sexual_pref:
  1: Straight
  2: Homo
  3: Bi


