locked_tips:
  - "Always look great, whatever your income. Gorgeous hair and some lipstick with rags will still turn his head. You have the advantage. You are the woman. Look your best as you could meet a potential Mr. Right anywhere at any time."
  - "Never reveal information you don't have to. An enigmatic woman drives men wild."
  - "Keep dates brief, but your men interested. Less is always more."
  - "Try and stay in shape and involve some fitness regime at a gym. However much you hate it, your Mr. Right loves your body as much as your mind."
  - "Let your man pay. If he is interested, he is interested enough to ensure you eat well and get home safely in a cab."
  - "Ensure you receive flowers. If he doesn't know what a florist is, dump him."
  - "Never ever sleep with a guy until he has fallen for you. Sex early in your dating game plan will ruin everything."
  - "Always keep a guy waiting and never turn up early. It is a lady's perogative."
  - "Never be available when he wants you to be. Never be at the end of a phone when he calls and always let him leave a message or two first before replying."
  - "If he is available Tuesday, you are available Thursday."
  - "Weekend shopping trips with girlfriends are sacred and not available for dates."
  - "Keep your man standing on quicksand by shifting landmarks and goalposts constantly."
  - "Ensure you are a good kisser. Men will walk away if you cannot kiss. Practice on a mirror if you have to."
  - "Never ever talk about previous boyfriends, particularly their prowess in the bedroom. Your ex-boyfriends are your business only."
  - "Never assume anything about your date until you choose to know him better. You cannot always tell by looking."
  - "If any man shows the slightest signs of possessiveness or insecurity, run like the wind. Life is too short for boys."
  - "If his shoes or hygiene are a disgrace, dump him."
  - "Never talk too much about your father and how your date measures up in comparison."
  - "Never ever come across as too available or too desperate. He will run a mile. He is the one doing the chasing."
  - "If the guy in the corner is gorgeous, go get him and create the need in him for you. Never wait for men to come to you because you may watch him leave with someone else."
  - "You may well have all the bodily functions of a man, just try not to demonstrate them early on."
  - "If you want a child, don't mention it on the first few dates."
  - "Never ever criticize his mother unless you want to remain single."
